#!/bin/bash

# lightsailのコンテナサービス名
SERVICE_NAME=playground

AWS_PROFILE=deploy-playground

DEPLOYMENT_DIR=$(pwd)/deployment
DOCKER_DIR=$(pwd)/docker

# container image name
APP_IMAGE_NAME=hanabi-app:latest
WEB_IMAGE_NAME=hanabi-web:latest

# build images
docker buildx build --no-cache --platform linux/amd64 -t "$APP_IMAGE_NAME" --target prod -f "$DOCKER_DIR"/php/Dockerfile --load .
docker buildx build --no-cache --platform linux/amd64 -t "$WEB_IMAGE_NAME" --target prod -f "$DOCKER_DIR"/nginx/Dockerfile --load .

# push images
aws lightsail push-container-image --profile "$AWS_PROFILE" --service-name "$SERVICE_NAME" --label app --image "$APP_IMAGE_NAME"
aws lightsail push-container-image --profile "$AWS_PROFILE" --service-name "$SERVICE_NAME" --label web --image "$WEB_IMAGE_NAME"

# build container.json
LIGHTSAIL_CONTAINERS=$(aws lightsail get-container-images --profile "$AWS_PROFILE" --service-name "$SERVICE_NAME")

APP_IMAGE=$(echo "$LIGHTSAIL_CONTAINERS" | jq --raw-output 'limit(1; .containerImages[] | select(.image | contains("app")) | .image)')
WEB_IMAGE=$(echo "$LIGHTSAIL_CONTAINERS" | jq --raw-output 'limit(1; .containerImages[] | select(.image | contains("web")) | .image)')

TMP_DEPLOYMENT_FILE_NAME=template-container-deployment.json
DEPLOYMENT_FILE_NAME=container-deployment.json

sed -e "s/<APP_IMAGE>/$APP_IMAGE/" \
    -e "s/<WEB_IMAGE>/$WEB_IMAGE/" \
    "$DEPLOYMENT_DIR"/"$TMP_DEPLOYMENT_FILE_NAME" > "$DEPLOYMENT_DIR"/"$DEPLOYMENT_FILE_NAME"

# create deployment
aws lightsail create-container-service-deployment \
  --service-name "$SERVICE_NAME" \
  --profile $AWS_PROFILE \
  --cli-input-json file://"$DEPLOYMENT_DIR"/"$DEPLOYMENT_FILE_NAME"