version: "3.9"
services:
  app:
    build: src
    volumes:
      - ./src:/var/www/html

  nginx:
    build:
      context: .
      dockerfile: ./docker/nginx/local/Dockerfile
    ports:
      - "8000:80"
    depends_on:
      - app


