name: CleanUpImages
on:
  workflow_dispatch:
jobs:
  clean:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Setup AWS cli and lightsail plugin
        run: |
          curl "https://awscli.amazonaws.com/awscli-exe-linux-x86_64.zip" -o "awscliv2.zip"
          unzip awscliv2.zip
          sudo ./aws/install --update
          curl "https://s3.us-west-2.amazonaws.com/lightsailctl/latest/linux-amd64/lightsailctl" -o "/usr/local/bin/lightsailctl"
          sudo chmod +x /usr/local/bin/lightsailctl
      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ secrets.AWS_REGION }}
      - name: Clean up
        run: |
          LIGHTSAIL_CONTAINER_IMAGES=$(aws lightsail get-container-images --service-name ${{ secrets.LIGHTSAIL_SERVICE_NAME }} | jq '.containerImages | reverse')

          # Remove all app_images other than latest
          APP_IMAGES=$(echo "$LIGHTSAIL_CONTAINER_IMAGES" | jq '.[] | select(contains({image: "app"}))' | jq -s '.')
          APP_IMAGE_LENGTH=$(echo "$APP_IMAGES" | jq 'length')
          if [ "$APP_IMAGE_LENGTH" -gt 2 ]; then
            for i in `seq 0 $((${APP_IMAGE_LENGTH} - 2))`; do
              IMAGE_NAME=$(echo "$APP_IMAGES" | jq -r '.['"$i"'] | .image')
              aws lightsail delete-container-image --service-name ${{ secrets.LIGHTSAIL_SERVICE_NAME }} --image "$IMAGE_NAME"
            done
          fi
          
          # Remove all web_images other than latest
          WEB_IMAGES=$(echo "$LIGHTSAIL_CONTAINER_IMAGES" | jq '.[] | select(contains({image: "web"}))' | jq -s '.')
          WEB_IMAGE_LENGTH=$(echo "$WEB_IMAGES" | jq 'length')
          if [ "$WEB_IMAGE_LENGTH" -gt 2 ]; then
            for i in `seq 0 $((${WEB_IMAGE_LENGTH} - 2))`; do
              IMAGE_NAME=$(echo "$WEB_IMAGES" | jq -r '.['"$i"'] | .image')
              aws lightsail delete-container-image --service-name ${{ secrets.LIGHTSAIL_SERVICE_NAME }} --image "$IMAGE_NAME"
            done
          fi