name: Migration
on:
  push:
    branches:
      - "gh-migration"
jobs:
  tagpr:
    runs-on: ubuntu-latest
    env:
      GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    steps:
      - uses: actions/checkout@v3
      - uses: Songmu/tagpr@v1
        id: run-tagpr
  migrate:
    runs-on: ubuntu-latest
    if: contains(github.event.pull_request.labels.*.name, 'CoolWord')
    steps:
      - uses: actions/checkout@v3
      - name: Variables
        id: variables
        run: |
          echo "foo"
  test:
    runs-on: ubuntu-latest
    if: "steps.run-tagpr.outputs.tag != ''"
    steps:
      - name: test
        run: |
          echo ${{ steps.run-tagpr.outputs.tag }}
