name: Migration
on:
  pull_request:
    types:
      - labeled
    branches:
      - "gh-migration"
jobs:
  tagpr:
    runs-on: ubuntu-latest
    outputs:
      tagpr-tag: ${{ steps.run-tagpr.outputs.tag }}
    env:
      GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    steps:
      - uses: actions/checkout@v3
      - uses: Songmu/tagpr@v1
        id: run-tagpr
  migrate:
    runs-on: ubuntu-latest
    env:
      GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    steps:
      - uses: actions/checkout@v3
      - name: Variables
        id: variables
        if: contains(github.event.pull_request.labels.*.name, 'CoolWord')
        run: |
          echo "foo"
  test:
    needs: tagpr
    if: needs.tagpr.outputs.tagpr-tag != ''
    env:
      GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: test
        run: |
          echo ${{ needs.tagpr.outputs.tagpr-tag }}
  test2:
    env:
      GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: test2
        run: |
          echo contains(github.event.pull_request.labels.*.name, 'CoolWord')