name: Migration
on:
  push:
    branches:
      - "gh-migration"
jobs:
  migrate:
    runs-on: ubuntu-latest
    steps:
      - name: Variables
        id: variables
        run: |
          echo ${GITHUB_REF#refs/tags/}
