name: Migration
on:
  push:
    branches:
      - "gh-migration"
jobs:
  migrate:
    runs-on: ubuntu-latest
    # if: contains(github.event.pull_request.labels.*.name, 'CoolWord')
    steps:
      - name: Variables
        id: variables
        run: |
          for v in "${{ github.event.pull_request.labels.*.name }}[@]"; do
            echo "{$v}"
          done
