name: Phpstan
on:
  push:
    branches:
      - '**'
jobs:
  phpunit:
    name: phpstan
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Init
        run: make setup
      - name: Run phpstan
        run: make phpstan
